server:
  port: 9080

spring:
  application:
    name: demo
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fruit?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  #Redis相关配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 12345
#配置ACTIVEMQ
#  activemq:
#    broker-url: tcp://127.0.0.1:61616
#    user: admin
#    password: admin
#    packages:
#      trust-all: true  #信任包
  jms:
    pub-sub-domain: false #false = Queue    true = Topic
    template:
      delivery-mode: persistent   #acticemq 在SpringBoot中的持久化
#kafka
  kafka:
    bootstrap-servers: 192.168.10.177:9092
    producer:
#      生产者序列化器
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      重试次数
      retries: 1

    consumer:
#      消费者序列化器
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      消费者消费的group_id
      group-id: kafkaTest1


#自定义队列名字
myqueue: boot-activemq-queue
mytopic: bppt-activemq-topic




pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


mybatis:
  type-aliases-package: com.lwy.demo.entity
  mapper-locations: mapper/*.xml


#配置日志级别  debug info 常用
logging:
  level:
    root: info
#    输出到文件  不指定路径再当前项目下生成  name 为文件的名字
  file:
    name: springbootstudy-file.log


#es
#elasticsearch:
#  host: 127.0.0.1
#  port: 9200
















